
version: "3.8"

services:
  runner:
    restart: always
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner2    
    networks:
      - gitlab-network 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./config:/etc/gitlab-runner:z

  register-runner:
    restart: 'no'
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-register
    networks:
      - gitlab-network
    environment:
      - CI_SERVER_URL=${GITLAB_URL}
      - REGISTRATION_TOKEN=${RUNNER_TOKEN}
    volumes:
      # - /home/daboogie/projects/gitlab/runner2/setup_runner.sh:/etc/gitlab-runner/setup_runner.sh
      - ./config:/etc/gitlab-runner:z
    # command: /etc/gitlab-runner/setup_runner.sh

    command:
      - register
      - --non-interactive
      - --locked=false
      - --url=${GITLAB_URL}
      - --token=${RUNNER_TOKEN}
      - --executor=docker
      - --docker-privileged=true
      - --docker-image=docker:24.0.5
      - --description=docker-runner
      - --docker-network-mode=host
      # - --cache-insecure=false
      # - --docker-dns=172.18.0.1
      # - --docker-network-mode=gitlab-network
      # - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock

networks:
  gitlab-network:
    external: true